/* ============================================================
   CENTINELA CODE — BUSCADORES PRINCIPALES
   Buscador global + buscador exclusivo de infracciones
   ============================================================ */
(function () {
  "use strict";
  const DATA_FILES = [
    ["infracciones", "./data/infracciones.json"],
    ["tráfico · infracciones", "./data/infracciones_trafico.json"],
    ["LOPSC", "./data/lopsc.json"],
    ["Código Penal", "./data/codigo_penal.json"],
    ["Menores", "./data/normativa_menores.json"],
    ["Violencia de género", "./data/normativa_violencia_genero.json"],
    ["Ordenanzas", "./data/ordenanzas.json"],
    ["Animales", "./data/normativa_animales.json"],
    ["Tráfico", "./data/normativa_trafico.json"],
    ["Ley 2/1986", "./data/ley_2_86.json"],
    ["LECrim", "./data/lecrim.json"],
    ["Extranjería", "./data/extranjeria.json"],
    ["Seguridad privada", "./data/seguridad_privada.json"],
    ["Espectáculos públicos", "./data/espectaculos_publicos.json"],
    ["Medio ambiente y ruidos", "./data/medio_ambiente_ruidos.json"],
    ["Reglamento de armas", "./data/reglamento_armas.json"],
    ["Policías Locales Andalucía", "./data/policias_locales_andalucia.json"],
    ["Ley 39/2015", "./data/ley_39_2015.json"],
    ["Ley 7/1985", "./data/ley_7_1985.json"],
    ["Ley 5/2010 Andalucía", "./data/ley_5_2010_andalucia.json"]
  ];
  const STOP = new Set(["a","al","ante","bajo","con","contra","de","del","desde","durante","el","en","entre","hacia","hasta","la","las","lo","los","para","por","segun","sin","sobre","un","una","unos","unas","y","o","que"]);
  const SYN = {"ruido":["ruidos","sonido","musica","molestias","acustica","decibelios"],"alcohol":["alcoholemia","bebida","embriaguez","etilometro"],"drogas":["estupefacientes","sustancias","narcoticos","psicotropicos"],"arma":["armas","navaja","cuchillo","arma blanca","pistola","revolver"],"agresion":["agredir","agresiones","golpear","lesiones","violencia","ataque"],"desobediencia":["desobedecer","resistencia","obediencia","requerimiento"],"seguro":["poliza","aseguramiento","soa","sin seguro"],"carnet":["permiso","licencia","conducir","conduccion"],"patinete":["vmp","vehiculo movilidad personal","vehiculo de movilidad personal"],"animal":["animales","perro","perros","mascota","mascotas"],"menor":["menores","niño","niña","adolescente"]};
  let indiceGlobal=[], indiceInfracciones=[], cargado=false;
  function norm(v){return String(v==null?"":v).toLowerCase().normalize("NFD").replace(/[\u0300-\u036f]/g,"").replace(/\s+/g," ").trim()}
  function tokens(q){return norm(q).split(/[^a-z0-9.]+/).filter(Boolean).filter(x=>!STOP.has(x))}
  function valueString(v){if(v==null)return "";if(typeof v!=="object")return String(v);if(Array.isArray(v))return v.slice(0,80).map(valueString).join(" ");return Object.entries(v).slice(0,80).map(([k,val])=>`${k} ${valueString(val)}`).join(" ")}
  function pick(o,names){if(!o||typeof o!=="object")return "";const e=Object.entries(o);for(const n of names){const h=e.find(([k])=>norm(k)===norm(n));if(h&&h[1]!=null&&typeof h[1]!=="object")return String(h[1])}for(const n of names){const h=e.find(([k])=>norm(k).includes(norm(n)));if(h&&h[1]!=null&&typeof h[1]!=="object")return String(h[1])}return ""}
  function isLikelyInfraction(o,source){if(!o||typeof o!=="object"||Array.isArray(o))return false;const keys=Object.keys(o).map(norm).join(" "),src=/infracc/.test(norm(source)),san=/sancion|multa|cuantia|importe/.test(keys),art=/articulo|art|article|precepto|codigo|código/.test(keys),con=/conducta|hechos|descripcion|descripción|description|infraccion|tipificacion|tipificación/.test(keys),sev=/leve|grave|muy grave|gravedad/.test(valueString(o).toLowerCase());return src||san||(art&&con)||(art&&sev)}
  function walk(v,source,path,out,depth){if(depth>8||v==null)return;if(Array.isArray(v)){v.forEach((x,i)=>walk(x,source,`${path}[${i}]`,out,depth+1));return}if(typeof v!=="object")return;const flat=valueString(v),article=pick(v,["articulo","artículo","article","art","precepto","codigo","código","numero","número"]),title=pick(v,["titulo","título","title","nombre","name","denominacion","denominación","epigrafe","epígrafe"]),desc=pick(v,["descripcion","descripción","description","texto","text","contenido","content","conducta","hechos","tipificacion","tipificación"]),severity=pick(v,["gravedad","severity","tipo","clasificacion","clasificación"]),amount=pick(v,["cuantia","cuantía","importe","importe_min","importe_max","multa","sancion","sanción"]),inf=isLikelyInfraction(v,source);if(article||title||desc||inf)out.push({source,path,article:article||"",title:title||"",description:desc||flat.slice(0,5000),severity:severity||"",amount:amount||"",isInfraction:inf,raw:v,search:norm([source,article,title,desc,severity,amount,flat].join(" "))});Object.entries(v).forEach(([k,x])=>{if(x&&typeof x==="object")walk(x,source,`${path}.${k}`,out,depth+1)})}
  async function cargarIndice(){if(cargado)return;const results=await Promise.all(DATA_FILES.map(async([source,url])=>{try{const r=await fetch(url,{cache:"no-cache"});if(!r.ok)throw Error(r.status);const out=[];walk(await r.json(),source,"$",out,0);return out}catch(e){console.warn("Buscadores: no se pudo cargar",url,e);return []}}));indiceGlobal=results.flat();indiceInfracciones=indiceGlobal.filter(x=>x.isInfraction);indiceInfracciones.sort((a,b)=>(/infracciones/.test(norm(a.source))?0:1)-(/infracciones/.test(norm(b.source))?0:1));cargado=true}
  function score(r,q){const ts=tokens(q),a=norm(r.article),t=norm(r.title),d=norm(r.description),s=norm(r.source),all=r.search;let n=0;if(a===norm(q)||a.replace(/\s/g,"")===norm(q).replace(/\s/g,""))n+=100;if(t===norm(q))n+=80;if(a.includes(norm(q)))n+=55;if(t.includes(norm(q)))n+=45;if(s.includes(norm(q)))n+=30;if(d.includes(norm(q)))n+=20;const ex=new Set(ts);ts.forEach(x=>(SYN[x]||[]).forEach(y=>ex.add(norm(y))));ex.forEach(x=>{if(all.includes(x))n+=3;if(a.includes(x))n+=18;else if(t.includes(x))n+=12;else if(d.includes(x))n+=6});return n}
  function esc(v){return String(v==null?"":v).replace(/[&<>'"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;","\"":"&quot;"}[c]))}
  function excerpt(text,q){const clean=String(text||"").replace(/\s+/g," ").trim(),term=norm(q).split(/\s+/).find(x=>x.length>2)||"",idx=term?norm(clean).indexOf(term):-1;return idx>80?"…"+clean.slice(idx-80,idx+260)+"…":clean.slice(0,340)+(clean.length>340?"…":"")}
  function unique(a){const seen=new Set();return a.filter(r=>{const k=norm(`${r.source}|${r.article}|${r.title}|${r.description.slice(0,160)}`);if(seen.has(k))return false;seen.add(k);return true})}
  function navigate(s){document.querySelector(`[data-section="${s}"]`)?.click()}
  function useInActa(r){navigate("actas");setTimeout(()=>{document.getElementById("newActaButton")?.click();setTimeout(()=>{const i=document.getElementById("actaInfraccion"),c=document.getElementById("actaCuantia"),p=document.getElementById("actaInfraccionPreview");if(i){i.value=r.article||r.title||"";i.dispatchEvent(new Event("input",{bubbles:true}));i.dispatchEvent(new Event("change",{bubbles:true}))}if(c&&r.amount){c.value=r.amount;c.dispatchEvent(new Event("input",{bubbles:true}))}if(p){p.classList.remove("hidden");p.innerHTML=`<strong>${esc(r.title||r.description.slice(0,180))}</strong><small>${esc(r.source)}${r.article?` · Art. ${esc(r.article)}`:""}${r.severity?` · ${esc(r.severity)}`:""}</small>`}if(typeof window.mostrarToast==="function")window.mostrarToast("Infracción cargada en el acta")},120)},80)}
  function showViewer(r){navigate("normativa");setTimeout(()=>{const v=document.getElementById("normativaViewer"),c=document.getElementById("viewerContent");if(!v||!c)return;const t=document.getElementById("viewerTitle"),s=document.getElementById("viewerSubtitle");if(t)t.textContent=r.title||r.source;if(s)s.textContent=`${r.source}${r.article?` · Art. ${r.article}`:""}`;c.innerHTML=`<div class="buscador-viewer-card"><h3>${esc(r.article?`Artículo ${r.article}`:r.title||r.source)}</h3><p>${esc(r.description||"Sin texto disponible.")}</p>${r.severity?`<p><strong>Gravedad:</strong> ${esc(r.severity)}</p>`:""}${r.amount?`<p><strong>Sanción/cuantía:</strong> ${esc(r.amount)}</p>`:""}</div>`;v.classList.remove("hidden")},100)}
  function render(container,count,results,q){count.textContent=results.length;if(!results.length){container.innerHTML=`<div class="bc-empty"><div>🔎</div><strong>No se han encontrado resultados</strong><span>Prueba con otra palabra, artículo, código o conducta.</span></div>`;return}container.innerHTML=results.slice(0,40).map(r=>`<article class="bc-result-card"><div class="bc-result-top"><span class="bc-result-type ${r.isInfraction?"is-infraction":""}">${r.isInfraction?"INFRACCIÓN":"NORMATIVA"}</span><span class="bc-result-source">${esc(r.source)}</span></div><h3>${esc(r.article?`Art. ${r.article}`:(r.title||r.source))}</h3>${r.title&&r.article?`<div class="bc-result-title">${esc(r.title)}</div>`:""}<p>${esc(excerpt(r.description,q))}</p><div class="bc-result-meta">${r.severity?`<span>⚠ ${esc(r.severity)}</span>`:""}${r.amount?`<span>💶 ${esc(r.amount)}</span>`:""}</div><div class="bc-result-actions"><button type="button" data-bc-view="${encodeURIComponent(JSON.stringify(r))}">Ver</button>${r.isInfraction?`<button type="button" class="primary" data-bc-acta="${encodeURIComponent(JSON.stringify(r))}">Usar en acta</button>`:""}</div></article>`).join("");container.querySelectorAll("[data-bc-view]").forEach(b=>b.addEventListener("click",()=>showViewer(JSON.parse(decodeURIComponent(b.dataset.bcView)))));container.querySelectorAll("[data-bc-acta]").forEach(b=>b.addEventListener("click",()=>useInActa(JSON.parse(decodeURIComponent(b.dataset.bcActa)))))}
  function search(q,only){const base=only?indiceInfracciones:indiceGlobal;return unique(base.map(r=>({r,s:score(r,q)})).filter(x=>x.s>0).sort((a,b)=>b.s-a.s).map(x=>x.r))}
  function injectStyles(){if(document.getElementById("bcStyles"))return;const s=document.createElement("style");s.id="bcStyles";s.textContent=`.bc-search-zone{margin:0 0 22px;display:grid;grid-template-columns:1fr 1fr;gap:14px}.bc-search-card{border:1px solid rgba(148,163,184,.18);border-radius:16px;padding:16px;background:linear-gradient(145deg,rgba(15,23,42,.96),rgba(30,41,59,.76));box-shadow:0 8px 24px rgba(0,0,0,.14)}.bc-search-card.inf{border-color:rgba(245,158,11,.28)}.bc-search-card h3{margin:0 0 4px;font-size:1rem;color:#f8fafc}.bc-search-card p{margin:0 0 12px;font-size:.78rem;color:#94a3b8;line-height:1.35}.bc-input-wrap{display:flex;align-items:center;gap:8px;border:1px solid #334155;border-radius:11px;background:#0f172a;padding:0 10px}.bc-input-wrap:focus-within{border-color:#3b82f6;box-shadow:0 0 0 2px rgba(59,130,246,.14)}.bc-input-wrap input{width:100%;border:0!important;outline:0!important;background:transparent!important;color:#fff!important;padding:11px 2px!important;font-size:.92rem}.bc-search-hint{margin-top:8px!important;font-size:.68rem!important;color:#64748b!important}.bc-results-zone{margin:0 0 20px}.bc-results-zone.hidden{display:none}.bc-results-title{display:flex;justify-content:space-between;align-items:center;margin:8px 2px 10px;color:#cbd5e1;font-size:.82rem}.bc-results-title strong{font-size:.72rem;color:#60a5fa}.bc-results-list{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:10px}.bc-result-card{border:1px solid rgba(148,163,184,.15);border-radius:14px;padding:13px;background:rgba(15,23,42,.7)}.bc-result-top{display:flex;justify-content:space-between;gap:8px;align-items:center}.bc-result-type{font-size:.62rem;font-weight:800;letter-spacing:.05em;color:#60a5fa}.bc-result-type.is-infraction{color:#fbbf24}.bc-result-source{font-size:.62rem;color:#64748b;text-align:right}.bc-result-card h3{margin:7px 0 4px;color:#f8fafc;font-size:.9rem}.bc-result-title{font-size:.72rem;color:#93c5fd;margin-bottom:6px}.bc-result-card p{margin:0;color:#94a3b8;font-size:.72rem;line-height:1.4}.bc-result-meta{display:flex;gap:8px;flex-wrap:wrap;margin-top:8px;font-size:.65rem;color:#a5b4fc}.bc-result-actions{display:flex;gap:7px;margin-top:10px}.bc-result-actions button{flex:1;border:1px solid #334155;background:#1e293b;color:#e2e8f0;border-radius:8px;padding:8px;font-size:.72rem;cursor:pointer}.bc-result-actions button.primary{border-color:#2563eb;background:#1d4ed8;color:#fff}.bc-empty{padding:24px;text-align:center;border:1px dashed #334155;border-radius:14px;color:#94a3b8}.bc-empty strong{display:block;color:#e2e8f0;font-size:.85rem}.bc-empty span{display:block;font-size:.72rem;margin-top:4px}.buscador-viewer-card{padding:4px}.buscador-viewer-card h3{margin-top:0}.buscador-viewer-card p{line-height:1.55}@media(max-width:760px){.bc-search-zone{grid-template-columns:1fr}.bc-results-list{grid-template-columns:1fr}.bc-search-card{padding:14px}}`;document.head.appendChild(s)}
  function injectUI(){const home=document.getElementById("section-home"),quick=home?.querySelector(".quick-actions");if(!home||!quick||document.getElementById("bcSearchZone"))return;const z=document.createElement("div");z.id="bcSearchZone";z.className="bc-search-zone";z.innerHTML=`<div class="bc-search-card"><h3>🔎 Buscador global</h3><p>Busca en toda la normativa, artículos, códigos e infracciones de Centinela Code.</p><div class="bc-input-wrap"><span>⌕</span><input id="bcGlobalInput" type="search" autocomplete="off" placeholder="Ej.: desobediencia, art. 36.16, ruidos…"></div><p class="bc-search-hint">Incluye leyes, LOPSC, tráfico, ordenanzas, Código Penal y demás bases.</p></div><div class="bc-search-card inf"><h3>⚠️ Buscador de infracciones</h3><p>Busca exclusivamente conductas sancionables e infracciones.</p><div class="bc-input-wrap"><span>⚠</span><input id="bcInfInput" type="search" autocomplete="off" placeholder="Ej.: alcohol, arma, ruido, seguro…"></div><p class="bc-search-hint">Los resultados se limitan al índice de infracciones detectado en las bases.</p></div>`;quick.insertAdjacentElement("afterend",z);const rz=document.createElement("div");rz.id="bcResultsZone";rz.className="bc-results-zone hidden";rz.innerHTML=`<div class="bc-results-title"><span id="bcResultsLabel">Resultados</span><strong id="bcResultsCount">0</strong></div><div class="bc-results-list" id="bcResultsList"></div>`;z.insertAdjacentElement("afterend",rz);const gi=document.getElementById("bcGlobalInput"),ii=document.getElementById("bcInfInput"),list=document.getElementById("bcResultsList"),count=document.getElementById("bcResultsCount"),label=document.getElementById("bcResultsLabel");let timer=null;function run(input,only){clearTimeout(timer);timer=setTimeout(async()=>{const q=input.value.trim();if(q.length<2){rz.classList.add("hidden");return}await cargarIndice();const res=search(q,only);label.textContent=only?`Infracciones para «${q}»`:`Resultados globales para «${q}»`;rz.classList.remove("hidden");render(list,count,res,q)},120)}gi.addEventListener("input",()=>{if(ii.value)ii.value="";run(gi,false)});ii.addEventListener("input",()=>{if(gi.value)gi.value="";run(ii,true)});gi.addEventListener("keydown",e=>{if(e.key==="Enter"){e.preventDefault();run(gi,false)}});ii.addEventListener("keydown",e=>{if(e.key==="Enter"){e.preventDefault();run(ii,true)}})}
  async function init(){injectStyles();injectUI();try{await cargarIndice()}catch(e){console.warn("Buscadores no inicializados",e)}}if(document.readyState==="loading")document.addEventListener("DOMContentLoaded",init,{once:true});else init();
})();