/* CENTINELA IA V4 — INTERNET FIRST + REPOSITORIO FALLBACK */
(function(){
  "use strict";
  const IA_URL="https://okuygqbaliaeavhyezri.supabase.co/functions/v1/centinela-ia";
  const TIMEOUT=22000, MAX=2, BREAKER=45000;
  const DATA=[["Infracciones","./data/infracciones.json"],["Tráfico","./data/infracciones_trafico.json"],["LOPSC","./data/lopsc.json"],["Código Penal","./data/codigo_penal.json"],["Menores","./data/normativa_menores.json"],["Violencia de género","./data/normativa_violencia_genero.json"],["Ordenanzas","./data/ordenanzas.json"],["Animales","./data/normativa_animales.json"],["Tráfico","./data/normativa_trafico.json"],["Ley 2/1986","./data/ley_2_86.json"],["LECrim","./data/lecrim.json"],["Extranjería","./data/extranjeria.json"],["Seguridad privada","./data/seguridad_privada.json"],["Espectáculos públicos","./data/espectaculos_publicos.json"],["Medio ambiente y ruidos","./data/medio_ambiente_ruidos.json"],["Reglamento de armas","./data/reglamento_armas.json"],["Policías Locales Andalucía","./data/policias_locales_andalucia.json"],["Ley 39/2015","./data/ley_39_2015.json"],["Ley 7/1985","./data/ley_7_1985.json"],["Ley 5/2010 Andalucía","./data/ley_5_2010_andalucia.json"]];
  const SYN={beber:["bebida","alcohol","consumo","botellon","via publica","bebiendo"],bebiendo:["beber","bebida","alcohol","consumo","botellon","via publica"],alcohol:["bebida","beber","consumo","botellon","via publica","embriaguez","ebriedad"],borracho:["alcohol","embriaguez","ebriedad","intoxicado","bebida"],borracha:["alcohol","embriaguez","ebriedad","intoxicada","bebida"],extranjero:["extranjeria","documentacion","documento","estancia","identificacion"],extranjera:["extranjeria","documentacion","documento","estancia","identificacion"],documentar:["documentacion","documento","identificacion","extranjero","extranjeria"],documentacion:["documentar","documento","identificacion","extranjero","extranjeria"],indocumentado:["documentacion","documento","identificacion","extranjero","extranjeria"],indocumentada:["documentacion","documento","identificacion","extranjera","extranjeria"],carnet:["permiso","conduccion","conducir","licencia"],conducir:["conduccion","permiso","licencia","vehiculo"],niño:["menor","menores","edad"],nino:["menor","menores","edad"],menor:["menores","edad","niño","nino"],calle:["via publica","espacio publico","publico"],botellon:["alcohol","bebida","via publica","consumo"],ruido:["ruidos","musica","molestias","decibelios"],arma:["armas","arma blanca","navaja","cuchillo"]};
  const STOP=new Set("a al ante bajo con contra de del desde durante el en entre hacia hasta la las lo los para por segun sin sobre un una unos unas y o que mi su".split(" "));
  let cache=null,breakerUntil=0,progress=null;
  const norm=s=>String(s??"").toLowerCase().normalize("NFD").replace(/[\u0300-\u036f]/g,"").replace(/\s+/g," ").trim();
  const tok=s=>norm(s).split(/[^a-z0-9.]+/).filter(x=>x.length>1&&!STOP.has(x));
  function pick(o,names){if(!o||typeof o!=="object"||Array.isArray(o))return"";for(const n of names){const e=Object.entries(o).find(([k])=>norm(k)===norm(n));if(e&&e[1]!=null&&typeof e[1]!=="object")return String(e[1]);}return"";}
  function flat(v,d=0){if(d>4||v==null)return"";if(typeof v!=="object")return String(v);if(Array.isArray(v))return v.slice(0,30).map(x=>flat(x,d+1)).join(" ");return Object.entries(v).slice(0,60).map(([k,x])=>k+" "+flat(x,d+1)).join(" ");}
  function records(v,src,out=[],d=0){if(d>8||v==null||out.length>=6000)return out;if(Array.isArray(v)){v.forEach(x=>records(x,src,out,d+1));return out;}if(typeof v!=="object")return out;const article=pick(v,["articulo","artículo","article","art","precepto"]),code=pick(v,["codigo","código"]),title=pick(v,["titulo","título","title","denominacion","denominación","epigrafe","epígrafe","nombre","name"]),description=pick(v,["conducta","descripcion","descripción","description","texto","text","contenido","content","tipificacion","tipificación","hechos","resumen"]),severity=pick(v,["gravedad","severity","clasificacion","clasificación"]),amount=pick(v,["cuantia","cuantía","importe","multa","sancion","sanción"]),foundation=pick(v,["fundamento","fundamento_juridico","fundamento jurídico","base_legal","base legal"]),action=pick(v,["actuacion_policial","actuación policial","actuacion","actuación","procedimiento"]);if(article||code||title||description||foundation||action)out.push({source:src,article,code,title,description,severity,amount,foundation,action,text:norm([src,article,code,title,description,severity,amount,foundation,action,flat(v)].join(" "))});Object.values(v).forEach(x=>{if(x&&typeof x==="object")records(x,src,out,d+1)});return out;}
  async function load(){if(cache)return cache;cache=Promise.all(DATA.map(async([src,url])=>{try{const r=await fetch(url+"?ia=v5",{cache:"force-cache"});return r.ok?records(await r.json(),src):[];}catch(_){return[];}})).then(a=>a.flat());return cache;}
  function ranked(q,all){const original=tok(q),expanded=new Set(original),phrase=norm(q);original.forEach(t=>(SYN[t]||[]).forEach(x=>expanded.add(norm(x))));return all.map(r=>{let score=0,matched=0;original.forEach(t=>{let hit=false;if(norm(r.article)===t){score+=140;hit=true;}if(norm(r.code)===t){score+=110;hit=true;}if(norm(r.title).includes(t)){score+=65;hit=true;}if(norm(r.description).includes(t)){score+=38;hit=true;}if(norm(r.source).includes(t))score+=25;if(r.text.includes(t)){score+=10;hit=true;}if(hit)matched++;});[...expanded].forEach(t=>{if(original.includes(t))return;if(norm(r.title).includes(t))score+=24;else if(norm(r.source).includes(t))score+=18;else if(r.text.includes(t))score+=7;});if(original.length>1&&matched===0)score=0;if(original.length>=3&&matched===1)score*=0.25;if(original.length>=3&&matched<2)score*=0.65;if(phrase&&r.text.includes(phrase))score+=220;return{r,s:score};}).filter(x=>x.s>0).sort((a,b)=>b.s-a.s).slice(0,10).map(x=>x.r);}
  function textOf(d){if(typeof d==="string")return d.trim();return d?.text?.trim()||d?.choices?.[0]?.message?.content?.trim()||d?.candidates?.[0]?.content?.parts?.[0]?.text?.trim()||d?.content?.trim()||"";}
  function errOf(d){return typeof d==="string"?d:d?.error?.message||d?.error||d?.message||"Proveedor remoto no disponible";}
  function retryable(status,msg){const m=norm(msg);return [429,500,502,503,504].includes(Number(status))||/high demand|rate limit|quota|overloaded|temporarily unavailable|timeout/.test(m);}
  function makeContext(hits){return hits.map((r,i)=>`${i+1}. NORMA: ${r.source}${r.article?` | ARTÍCULO: ${r.article}`:""}${r.code?` | CÓDIGO: ${r.code}`:""}${r.title?` | TÍTULO: ${r.title}`:""}${r.severity?` | GRAVEDAD: ${r.severity}`:""}${r.amount?` | SANCIÓN: ${r.amount}`:""}\nCONTENIDO: ${String(r.description||"").replace(/\s+/g," ").slice(0,1800)}\nFUNDAMENTO: ${String(r.foundation||"").replace(/\s+/g," ").slice(0,1200)}\nACTUACIÓN: ${String(r.action||"").replace(/\s+/g," ").slice(0,1200)}`).join("\n\n");}
  function fallback(q,hits){return JSON.stringify({resumen:hits.length?`Se han localizado ${hits.length} referencias normativas relacionadas. La calificación debe concretarse con los hechos y circunstancias comprobados.`:`No hay coincidencia normativa local suficiente para: ${q}.`,infracciones:hits.map(r=>({fuente:r.source,articulo:r.article,codigo:r.code,titulo:r.title,descripcion:r.description,gravedad:r.severity,cuantia:r.amount,fundamento:r.foundation,actuacion_policial:r.action})),articulos:hits.map(r=>r.article).filter(Boolean),fundamento:hits.map(r=>r.foundation).filter(Boolean).join(" "),actuacion_policial:hits.map(r=>r.action).filter(Boolean).join(" ")||"Comprobar identidad, hechos, circunstancias, precepto aplicable, competencia y pruebas antes de denunciar.",aviso:"Resultado de contingencia: verificar el precepto, la competencia y la cuantía aplicable antes de formalizar la denuncia."});}
  function promptPolicial(q){const texto=String(q||"").trim();if(/FORMATO JSON EXACTO|HECHOS DEL AGENTE|HECHOS ORIGINALES/i.test(texto))return texto;return `Eres CENTINELA IA, asistente profesional de apoyo para Policía Local en España. Responde exclusivamente a la consulta ACTUAL. Lenguaje claro, policial, objetivo, directo y operativo. No inventes artículos, leyes, sanciones, cuantías, competencias ni hechos. Distingue hechos acreditados de comprobaciones pendientes. Si una conducta depende de circunstancias, indícalas. No atribuyas automáticamente responsabilidad a terceros. Usa únicamente el contexto recibido y descarta coincidencias irrelevantes.\n\nEstructura, cuando proceda: Valoración; Infracción y artículo; Norma aplicable; Calificación; Sanción o rango de sanción; Fundamento jurídico; Método de actuación policial; Comprobaciones antes de denunciar. No devuelvas JSON, código, Markdown ni emojis. No uses la palabra Fuente.\n\nCONSULTA ACTUAL:\n${texto}`;}
  async function remote(q,ctx,modo){if(Date.now()<breakerUntil)throw Error("Proveedor remoto temporalmente saturado");let last;for(let i=0;i<MAX;i++){if(progress)progress(modo==="web_first"?(i?`Reintentando búsqueda web (${i+1}/${MAX})...`:"Buscando información oficial en Internet..."):(i?`Reintentando conexión (${i+1}/${MAX})...`:"Analizando normativa del repositorio..."));if(i)await new Promise(r=>setTimeout(r,1200*i));const c=new AbortController(),tm=setTimeout(()=>c.abort(),TIMEOUT);try{const res=await fetch(IA_URL,{method:"POST",headers:{"Content-Type":"application/json","Accept":"application/json"},body:JSON.stringify({pregunta:promptPolicial(q),contexto:ctx,modo}),signal:c.signal});const raw=await res.text();clearTimeout(tm);let d;try{d=JSON.parse(raw);}catch(_){d=raw;}if(res.ok){breakerUntil=0;if(progress)progress(modo==="web_first"?"Información web analizada.":"Respuesta normativa obtenida.");return d;}last=Error(errOf(d));if(!retryable(res.status,last.message))break;}catch(e){clearTimeout(tm);last=e;if(!retryable(0,e.message))break;}}breakerUntil=Date.now()+BREAKER;throw last||Error("Proveedor remoto no disponible");}
  async function ask(q,onProgress){q=String(q||"").trim();if(!q)return"Escribe una consulta para Centinela IA.";progress=typeof onProgress==="function"?onProgress:null;try{
    try{const web=await remote(q,"","web_first");if(web?.ok&&web?.web_found&&web?.text)return web.text;}catch(e){console.warn("Centinela IA web:",e);}
    if(progress)progress("No hay respuesta web suficientemente fiable. Buscando en el repositorio normativo...");
    const all=await load(),hits=ranked(q,all),ctx=makeContext(hits);
    try{const repo=await remote(q,ctx,"repository_fallback");const text=textOf(repo);if(text)return text;}catch(e){console.warn("Centinela IA repositorio:",e);if(progress)progress("IA remota no disponible. Activando motor normativo local...");}
    const result=fallback(q,hits);if(progress)progress("Resultado obtenido con el motor normativo local.");return result;
  }catch(e){console.error("Centinela IA:",e);return JSON.stringify({resumen:"Centinela IA no está disponible temporalmente.",infracciones:[],articulos:[],fundamento:"",actuacion_policial:"Comprueba la conexión y consulta la normativa local manualmente."});}finally{progress=null;}}
  window.preguntarCentinelaIA=ask;window.CentinelaIA={preguntar:ask,recargarDatos:()=>{cache=null;return load();},estado:()=>({remoto:Date.now()>=breakerUntil,breakerUntil}),setCallbackProgreso:f=>{progress=typeof f==="function"?f:null}};
  console.info("Centinela IA V5 — Internet First + Repositorio Fallback activo");
})();
